EXPERIMENT:
  NAME: "byol_pretext"
  TAG: "baselines"
  PROJECT: "debug project"
  DEBUG: True
  REPETITION_NUM: 1 # Number of repetition times
  TASK: "pretext"
  RESUME : False  # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
DATASET:
  ROOT: "/home/song/datasets/MEG"
  TYPE: "DecMeg"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "BYOL"
  ARGS:
    BACKBONE: "varcnn"
    SIAMESE: True
    USE_MOMENTUM: True  # True for BYOL, False for SimSiam
    PROJECTION_DIM: 512
    PROJECTION_HIDDEN_SIZE: 4096
    TAU_BASE: 0.996
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "RegressionLoss"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "BYOL"
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.005
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.0001

