EXPERIMENT:
  NAME: "simclr_with_NTXent"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: False
  REPETITION_NUM: 1 # Number of repetition times
  TASK: "pretext"
  RESUME: False # Resume training
  CHECKPOINT: "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX: None # Choose index of checkpoint to start from. If None, uses the latest chkp
DATASET:
  ROOT: "/home/song/datasets/MEG"
  TYPE: "DecMeg"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "SimCLR"
  ARGS:
    BACKBONE: "varcnn"
    TEMPERATURE: 0.5
    SIAMESE: True
    PROJECTION_DIM: 128
    N_FEATURES: 4500
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "NT_Xent"
    ARGS:
      TEMPERATURE: 0.5
      # SOURCE_CHANNELS: 36
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 300
  LR: 0.05
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.0001
