EXPERIMENT:
  NAME: "byol_pretext"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: False
  REPETITION_NUM: 1 # Number of repetition times
  TASK: "pretext"
  RESUME : False # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
  CHECKPOINT_GAP: 10
DATASET:
  ROOT: "/home/song/datasets/EEG"
  TYPE: "sleepedf20"
  CHANNELS: 1
  POINTS: 3000
  NUM_CLASSES: 5
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "BYOL"
  ARGS:
    BACKBONE: "eegconvnet"
    SIAMESE: True
    USE_MOMENTUM: True  # True for BYOL, False for SimSiam
    HIDDEN_LAYER: -1
    PROJECTION_DIM: 256
    PROJECTION_HIDDEN_SIZE: 2048
    TAU_BASE: 0.996
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "RegressionLoss"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "BYOL"
  BATCH_SIZE: 512
  EPOCHS: 10
  LR: 0.0001
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.9
    MIN_LR: 0.0000001

