EXPERIMENT:
  NAME: "debug"
  TAG: ""
  PROJECT: ""
  DEBUG: True
  REPETITION_NUM: 1 # Number of repetition times
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 1024
MODEL:
  TYPE: "TimeNet"
  ARGS:
    SOURCE_CHANNELS: 36
    MAX_POOL: 2
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 100
  LR: 0.001
