EXPERIMENT:
  NAME: "varcnn"
  TAG: "reproduce"
  PROJECT: "base project"
  DEBUG: True
  REPETITION_NUM: 5 # Number of repetition times
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "varcnn"
  ARGS:
    MAX_POOL: 2
    DROP_OUT: 0.5
    SOURCE_CHANNELS: 36
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.0003
